#!/usr/bin/env python3
"""Build reports/final-comparison.md from every clip and long-form report available.

Scans reports/**/report.json (baselines, v0, v1 runs; sharded reports are merged by name prefix),
recomputes WER/CER with the shared normalizer from the stored ref/hyp pairs, and writes one table
(clip dev/test and long-form test) plus a per-test-day table for the best model.
"""
from __future__ import annotations

import glob
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

import jiwer

sys.path.insert(0, str(Path(__file__).resolve().parent))
from normalize import scoring_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    clip = defaultdict(list); lf = defaultdict(list)
    for f in glob.glob(str(ROOT / "reports" / "**" / "report.json"), recursive=True):
        if any(k in f for k in ("contaminated", "shardtest", "hftest", "/fleet/", "train-scan", "/sweep/", "error-analysis")):
            continue
        try:
            data = json.loads(Path(f).read_text())
        except Exception:  # noqa: BLE001
            continue
        name = Path(f).parent.name
        name = re.sub(r"-longform$", "", name); name = re.sub(r"-shard\d+$", "", name)
        pilot = name.startswith(("baseline-", "pilot-")) and "devtest" not in name
        # canonical model key: clip reports (devtest-<m>, v1-<m>) and long-form reports (lf-<m>, <m>-longform) merge
        name = re.sub(r"^(lf-|devtest-|v1-)", "", name); name = re.sub(r"(-longform|-ct2)$", "", name)
        if pilot:
            name += " (pilot 2-day split)"
        if "clips" in data:
            clip[name] += data["clips"]
        elif "days" in data:
            lf[name] += data["days"]
    rows = []
    for name in sorted(set(clip) | set(lf)):
        r = {"model": name}
        cs = clip.get(name, [])
        for split in ("dev", "test", "test_b"):   # test_b = data/splits_b.json, 20 held-out 5781 days (v5 onward)
            sel = [c for c in cs if c["split"] == split]
            if sel:
                refs = [scoring_text(c["ref"]) for c in sel]; hyps = [scoring_text(c["hyp"]) for c in sel]
                r[f"clip_{split}_wer"] = jiwer.wer(refs, hyps); r[f"clip_{split}_cer"] = jiwer.cer(refs, hyps); r[f"clip_{split}_n"] = len(sel)
        ds = lf.get(name, [])
        if ds:
            refs = [scoring_text(d.get("ref_text") or "") for d in ds]  # long-form reports store hyp; ref must be rebuilt
            r["lf_test_wer_reported"] = sum(d["wer"] * d["ref_words"] for d in ds) / max(1, sum(d["ref_words"] for d in ds))
            r["lf_test_cer_reported"] = sum(d["cer"] * d["ref_words"] for d in ds) / max(1, sum(d["ref_words"] for d in ds))
            r["lf_days"] = len(ds)
        rows.append(r)
    rows.sort(key=lambda r: (" (pilot" in r["model"], r.get("clip_test_wer", 9)))
    md = ["# Model comparison (auto-generated by pipeline/compare_runs.py)", "",
          "Clip-level WER/CER on the fixed dev/test days (`data/splits.json`) and on test_b (`data/splits_b.json`, 20 held-out 5781 days, scored from v5 on); long-form = whole test files decoded through the GPU path (auto windows since 2026-09-23).", "",
          "| model | clip dev WER | clip test WER | clip test CER | clip test_b WER | long-form test WER | long-form test CER | test clips / lf days |", "|---|---:|---:|---:|---:|---:|---:|---|"]
    for r in rows:
        f = lambda k: f"{r[k]:.3f}" if k in r else ""
        md.append(f"| {r['model']} | {f('clip_dev_wer')} | {f('clip_test_wer')} | {f('clip_test_cer')} | {f('clip_test_b_wer')} | {f('lf_test_wer_reported')} | {f('lf_test_cer_reported')} | {r.get('clip_test_n','')} / {r.get('lf_days','')} |")
    if rows and "clip_test_wer" in rows[0]:
        best = rows[0]["model"]; md += ["", f"## Per test day, best model: {best}", "", "| day | WER | CER | clips |", "|---|---:|---:|---:|"]
        by = defaultdict(list)
        for c in clip[best]:
            if c["split"] == "test": by[c["day"]].append(c)
        for day, cs in sorted(by.items()):
            refs = [scoring_text(c["ref"]) for c in cs]; hyps = [scoring_text(c["hyp"]) for c in cs]
            md.append(f"| {day} | {jiwer.wer(refs,hyps):.3f} | {jiwer.cer(refs,hyps):.3f} | {len(cs)} |")
    out = ROOT / "reports" / "final-comparison.md"; out.write_text("\n".join(md) + "\n")
    (ROOT / "reports" / "final-comparison.json").write_text(json.dumps(rows, indent=1))
    print("\n".join(md[:6 + len(rows)])); print("->", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
